service: pick-to-door
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  environment:
    MONGO_URI: mongodb+srv://pick2doorDbUser:xWl9bQrnZmmXYYK1@pick2door.syhdb.mongodb.net/pick-to-door 
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:DescribeLogGroups
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: '*'

functions:
  registerCustomer:
    handler: index.registerCustomer

  getCustomer:
    handler: index.getCustomer

  sendOtp:
    handler: index.sendOtp

  createLocation:
    handler: index.createLocation

  getLocationByUser:
    handler: index.getLocationByUser

  getLocation:
    handler: index.getLocation

  getItemTypes:
    handler: index.getItemTypes

  createDeliveryForm:
    handler: index.createDeliveryForm

  getDeliveryForm:
    handler: index.getDeliveryForm

  updateDeliveryData:
    handler: index.updateDeliveryData

resources:
  Resources:
    # AppSync API Definition
    Pick2DoorAppSyncAPI:
      Type: AWS::AppSync::GraphQLApi
      Properties:
        Name: Pick2DoorAppSyncAPI
        AuthenticationType: API_KEY

    Pick2DoorAppSyncAPIKey:
      Type: AWS::AppSync::ApiKey
      Properties:
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        Expires: 1765497600 # Expires on December 12, 2025

    # GraphQL Schema Definition
    Pick2DoorGraphApiSchema:
      Type: AWS::AppSync::GraphQLSchema
      Properties:
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        Definition: !Sub ${file(schema.graphql)}

    # IAM Role for AppSync to invoke Lambda functions
    AppSyncServiceRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: Pick2DoorAppSyncServiceRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: appsync.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: AppSyncLambdaInvokePolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource:
                    - !GetAtt RegisterCustomerLambdaFunction.Arn
                    - !GetAtt GetCustomerLambdaFunction.Arn
                    - !GetAtt SendOtpLambdaFunction.Arn
                    - !GetAtt CreateLocationLambdaFunction.Arn
                    - !GetAtt GetLocationByUserLambdaFunction.Arn
                    - !GetAtt GetLocationLambdaFunction.Arn
                    - !GetAtt GetItemTypesLambdaFunction.Arn
                    - !GetAtt CreateDeliveryFormLambdaFunction.Arn
                    - !GetAtt GetDeliveryFormLambdaFunction.Arn
                    - !GetAtt UpdateDeliveryDataLambdaFunction.Arn

    # Data Sources for AppSync
    RegisterCustomerDataSource:
      Type: AWS::AppSync::DataSource
      Properties:
        Name: RegisterCustomerDataSource
        Type: AWS_LAMBDA
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
        LambdaConfig:
          LambdaFunctionArn: !GetAtt RegisterCustomerLambdaFunction.Arn

    SendOtpDataSource:
      Type: AWS::AppSync::DataSource
      Properties:
        Name: SendOtpDataSource
        Type: AWS_LAMBDA
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
        LambdaConfig:
          LambdaFunctionArn: !GetAtt SendOtpLambdaFunction.Arn

    GetCustomerDataSource:
      Type: AWS::AppSync::DataSource
      Properties:
        Name: GetCustomerDataSource
        Type: AWS_LAMBDA
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
        LambdaConfig:
          LambdaFunctionArn: !GetAtt GetCustomerLambdaFunction.Arn

    CreateLocationDataSource:
      Type: AWS::AppSync::DataSource
      Properties:
        Name: CreateLocationDataSource
        Type: AWS_LAMBDA
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
        LambdaConfig:
          LambdaFunctionArn: !GetAtt CreateLocationLambdaFunction.Arn

    GetLocationByUserDataSource:
      Type: AWS::AppSync::DataSource
      Properties:
        Name: GetLocationByUserDataSource
        Type: AWS_LAMBDA
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
        LambdaConfig:
          LambdaFunctionArn: !GetAtt GetLocationByUserLambdaFunction.Arn

    GetLocationDataSource:
      Type: AWS::AppSync::DataSource
      Properties:
        Name: GetLocationDataSource
        Type: AWS_LAMBDA
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
        LambdaConfig:
          LambdaFunctionArn: !GetAtt GetLocationLambdaFunction.Arn

    GetItemTypesDataSource:
      Type: AWS::AppSync::DataSource
      Properties:
        Name: GetItemTypesDataSource
        Type: AWS_LAMBDA
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
        LambdaConfig:
          LambdaFunctionArn: !GetAtt GetItemTypesLambdaFunction.Arn

    # Delivery Form Data Sources
    CreateDeliveryFormDataSource:
      Type: AWS::AppSync::DataSource
      Properties:
        Name: CreateDeliveryFormDataSource
        Type: AWS_LAMBDA
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
        LambdaConfig:
          LambdaFunctionArn: !GetAtt CreateDeliveryFormLambdaFunction.Arn

    GetDeliveryFormDataSource:
      Type: AWS::AppSync::DataSource
      Properties:
        Name: GetDeliveryFormDataSource
        Type: AWS_LAMBDA
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
        LambdaConfig:
          LambdaFunctionArn: !GetAtt GetDeliveryFormLambdaFunction.Arn

    UpdateDeliveryDataDataSource:
      Type: AWS::AppSync::DataSource
      Properties:
        Name: UpdateDeliveryDataDataSource
        Type: AWS_LAMBDA
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
        LambdaConfig:
          LambdaFunctionArn: !GetAtt UpdateDeliveryDataLambdaFunction.Arn

    # Delivery Form Resolvers
    RegisterCustomerMutationResolver:
      Type: AWS::AppSync::Resolver
      Properties:
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        TypeName: Mutation
        FieldName: registerCustomer
        DataSourceName: !GetAtt RegisterCustomerDataSource.Name

    SendOtpMutationResolver:
      Type: AWS::AppSync::Resolver
      Properties:
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        TypeName: Mutation
        FieldName: sendOtp
        DataSourceName: !GetAtt SendOtpDataSource.Name

    GetCustomerQueryResolver:
      Type: AWS::AppSync::Resolver
      Properties:
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        TypeName: Query
        FieldName: getCustomer
        DataSourceName: !GetAtt GetCustomerDataSource.Name

    CreateLocationMutationResolver:
      Type: AWS::AppSync::Resolver
      Properties:
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        TypeName: Mutation
        FieldName: createLocation
        DataSourceName: !GetAtt CreateLocationDataSource.Name

    GetLocationByUserQueryResolver:
      Type: AWS::AppSync::Resolver
      Properties:
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        TypeName: Query
        FieldName: getLocationByUser
        DataSourceName: !GetAtt GetLocationByUserDataSource.Name

    GetLocationQueryResolver:
      Type: AWS::AppSync::Resolver
      Properties:
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        TypeName: Query
        FieldName: getLocation
        DataSourceName: !GetAtt GetLocationDataSource.Name

    GetItemTypesQueryResolver:
      Type: AWS::AppSync::Resolver
      Properties:
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        TypeName: Query
        FieldName: getItemTypes
        DataSourceName: !GetAtt GetItemTypesDataSource.Name

    CreateDeliveryFormMutationResolver:
      Type: AWS::AppSync::Resolver
      Properties:
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        TypeName: Mutation
        FieldName: createDeliveryForm
        DataSourceName: !GetAtt CreateDeliveryFormDataSource.Name

    GetDeliveryFormQueryResolver:
      Type: AWS::AppSync::Resolver
      Properties:
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        TypeName: Query
        FieldName: getDeliveryForm
        DataSourceName: !GetAtt GetDeliveryFormDataSource.Name

    UpdateDeliveryDataMutationResolver:
      Type: AWS::AppSync::Resolver
      Properties:
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        TypeName: Mutation
        FieldName: updateDeliveryData
        DataSourceName: !GetAtt UpdateDeliveryDataDataSource.Name

  Outputs:
    GraphQLAPIEndpoint:
      Value: !GetAtt Pick2DoorAppSyncAPI.GraphQLUrl
      Export:
        Name: GraphQLAPIEndpoint

    GraphQLAPIKey:
      Value: !Ref Pick2DoorAppSyncAPIKey
      Export:
        Name: GraphQLAPIKey