service: pick-to-door-dev
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: "ap-south-1"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:DescribeLogGroups"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "*"

functions:
  createUser:
    handler: index.createUser

resources:
  Resources:
    # AppSync API Definition
    Pick2DoorAppSyncAPI:
      Type: "AWS::AppSync::GraphQLApi"
      Properties:
        Name: "Pick2DoorAppSyncAPI"
        AuthenticationType: "API_KEY"

    Pick2DoorAppSyncAPIKey:
      Type: "AWS::AppSync::ApiKey"
      Properties:
        ApiId:
          Fn::GetAtt:
            - "Pick2DoorAppSyncAPI"
            - "ApiId"
        Expires: 1765497600 # Expires on December 12, 2025

    # GraphQL Schema Definition
    Pick2DoorGraphApiSchema:
      Type: "AWS::AppSync::GraphQLSchema"
      Properties:
        ApiId:
          Fn::GetAtt:
            - "Pick2DoorAppSyncAPI"
            - "ApiId"
        Definition:
          Fn::Sub: "${file(schema.graphql)}"

    # IAM Role for AppSync to invoke Lambda functions
    AppSyncServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "Pick2DoorAppSyncServiceRole"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service: "appsync.amazonaws.com"
              Action: "sts:AssumeRole"
        Policies:
          - PolicyName: "AppSyncLambdaInvokePolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "lambda:InvokeFunction"
                  Resource:
                    - Fn::GetAtt:
                        - CreateUserLambdaFunction
                        - Arn

    # Data Source linking AppSync to Lambda function for CreateUser
    CreateUserDataSource:
      Type: "AWS::AppSync::DataSource"
      Properties:
        Name: "CreateUserDataSource"
        Type: "AWS_LAMBDA"
        ApiId:
          Fn::GetAtt:
            - "Pick2DoorAppSyncAPI"
            - "ApiId"
        ServiceRoleArn:
          Fn::GetAtt:
            - "AppSyncServiceRole"
            - "Arn"
        LambdaConfig:
          LambdaFunctionArn:
            Fn::GetAtt:
              - CreateUserLambdaFunction
              - Arn

    # Resolver to connect GraphQL mutation to Lambda function for CreateUser
    CreateUserMutationResolver:
      Type: "AWS::AppSync::Resolver"
      Properties:
        ApiId:
          Fn::GetAtt:
            - "Pick2DoorAppSyncAPI"
            - "ApiId"
        TypeName: "Mutation"
        FieldName: "createUser"
        DataSourceName:
          Fn::GetAtt:
            - "CreateUserDataSource"
            - "Name"

  Outputs:
    GraphQLAPIEndpoint:
      Value:
        Fn::GetAtt:
          - "Pick2DoorAppSyncAPI"
          - "GraphQLUrl"
      Export:
        Name: "GraphQLAPIEndpoint"

    GraphQLAPIKey:
      Value:
        Ref: "Pick2DoorAppSyncAPIKey"
      Export:
        Name: "GraphQLAPIKey"
