service: pick-to-door-dev
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  environment:
    MONGO_URI: mongodb+srv://pick2doorDbUser:xWl9bQrnZmmXYYK1@pick2door.syhdb.mongodb.net/pick-to-door
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:DescribeLogGroups
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: '*'

functions:
  registerCustomer:
    handler: index.registerCustomer
  getCustomer:
    handler: index.getCustomer
  sendOtp:
    handler: index.sendOtp

resources:
  Resources:
    # AppSync API Definition
    Pick2DoorAppSyncAPI:
      Type: AWS::AppSync::GraphQLApi
      Properties:
        Name: Pick2DoorAppSyncAPI
        AuthenticationType: API_KEY

    Pick2DoorAppSyncAPIKey:
      Type: AWS::AppSync::ApiKey
      Properties:
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        Expires: 1765497600 # Expires on December 12, 2025

    # GraphQL Schema Definition
    Pick2DoorGraphApiSchema:
      Type: AWS::AppSync::GraphQLSchema
      Properties:
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        Definition: !Sub ${file(schema.graphql)}

    # IAM Role for AppSync to invoke Lambda functions
    AppSyncServiceRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: Pick2DoorAppSyncServiceRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: appsync.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: AppSyncLambdaInvokePolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource:
                    - !GetAtt RegisterCustomerLambdaFunction.Arn
                    - !GetAtt GetCustomerLambdaFunction.Arn
                    - !GetAtt SendOtpLambdaFunction.Arn

    # Data Source linking AppSync to Lambda function for RegisterCustomer
    RegisterCustomerDataSource:
      Type: AWS::AppSync::DataSource
      Properties:
        Name: RegisterCustomerDataSource
        Type: AWS_LAMBDA
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
        LambdaConfig:
          LambdaFunctionArn: !GetAtt RegisterCustomerLambdaFunction.Arn

    SendOtpDataSource:
      Type: AWS::AppSync::DataSource
      Properties:
        Name: SendOtpDataSource
        Type: AWS_LAMBDA
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
        LambdaConfig:
          LambdaFunctionArn: !GetAtt SendOtpLambdaFunction.Arn

    GetCustomerDataSource:
      Type: AWS::AppSync::DataSource
      Properties:
        Name: GetCustomerDataSource
        Type: AWS_LAMBDA
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
        LambdaConfig:
          LambdaFunctionArn: !GetAtt GetCustomerLambdaFunction.Arn

    # Resolver to connect GraphQL mutation to Lambda function for RegisterCustomer
    RegisterCustomerMutationResolver:
      Type: AWS::AppSync::Resolver
      Properties:
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        TypeName: Mutation
        FieldName: registerCustomer
        DataSourceName: !GetAtt RegisterCustomerDataSource.Name

    SendOtpMutationResolver:
      Type: AWS::AppSync::Resolver
      Properties:
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        TypeName: Mutation
        FieldName: sendOtp
        DataSourceName: !GetAtt SendOtpDataSource.Name

    GetCustomerQueryResolver:
      Type: AWS::AppSync::Resolver
      Properties:
        ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
        TypeName: Query
        FieldName: getCustomer
        DataSourceName: !GetAtt GetCustomerDataSource.Name

  Outputs:
    GraphQLAPIEndpoint:
      Value: !GetAtt Pick2DoorAppSyncAPI.GraphQLUrl
      Export:
        Name: GraphQLAPIEndpoint

    GraphQLAPIKey:
      Value: !Ref Pick2DoorAppSyncAPIKey
      Export:
        Name: GraphQLAPIKey