Resources:
  RegisterCustomerDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      Name: RegisterCustomerDataSource
      Type: AWS_LAMBDA
      ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !GetAtt RegisterCustomerLambdaFunction.Arn

  SendOtpDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      Name: SendOtpDataSource
      Type: AWS_LAMBDA
      ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !GetAtt SendOtpLambdaFunction.Arn

  GetCustomerDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      Name: GetCustomerDataSource
      Type: AWS_LAMBDA
      ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !GetAtt GetCustomerLambdaFunction.Arn

  CreateLocationDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      Name: CreateLocationDataSource
      Type: AWS_LAMBDA
      ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !GetAtt CreateLocationLambdaFunction.Arn

  GetLocationByUserDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      Name: GetLocationByUserDataSource
      Type: AWS_LAMBDA
      ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !GetAtt GetLocationByUserLambdaFunction.Arn

  GetLocationDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      Name: GetLocationDataSource
      Type: AWS_LAMBDA
      ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !GetAtt GetLocationLambdaFunction.Arn

  GetItemTypesDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      Name: GetItemTypesDataSource
      Type: AWS_LAMBDA
      ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !GetAtt GetItemTypesLambdaFunction.Arn

  # Delivery Form Data Sources
  CreateDeliveryFormDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      Name: CreateDeliveryFormDataSource
      Type: AWS_LAMBDA
      ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !GetAtt CreateDeliveryFormLambdaFunction.Arn

  GetDeliveryFormDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      Name: GetDeliveryFormDataSource
      Type: AWS_LAMBDA
      ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !GetAtt GetDeliveryFormLambdaFunction.Arn

  UpdateDeliveryDataDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      Name: UpdateDeliveryDataDataSource
      Type: AWS_LAMBDA
      ApiId: !GetAtt Pick2DoorAppSyncAPI.ApiId
      ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !GetAtt UpdateDeliveryDataLambdaFunction.Arn